<?php

// Returning the user
if ($this->success) {

    unset($this->user->password);

    // The object URL to reference it according to REST responses standards
    $url = $this->url(array(
        'controller' => 'User',
        'id'         => $this->user->id
    ));

    // Setting the header according to REST responses standards
    $this->response->setHeader('Location', $url)
                   ->setHttpResponseCode(201);

    // The user itself
    echo $this->json($this->user);

    return;

// Failed
} else {

    echo $this->json('Error: ' . $this->failedmessage);
    return;
}